services:
  postgres-db:
    image: postgres:16.4
    container_name: postgres
    restart: no
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: catalogue
      POSTGRES_PASSWORD: catalogue
      POSTGRES_DB: catalogue
    depends_on:
      - microservice-market.catalogue-service
      - kafka
  mongo-db:
    image: mongo:7.0.14
    container_name: mongo
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: order
    depends_on:
      - kafka
      - microservice-market.order-service
volumes:
  postgres_data:
  mongo_data: